language: python
python:
- '3.8'
install:
- pip install -r requirements.txt

script:
 - python -m pytest -v src/unittest/python/books_tests.py
 - python -m pytest -v src/unittest/python/library_tests.py

notifications:
  email:
    - ina.zyka1@gmail.com
